import React, { createContext, useContext } from 'react';
import { Screen, T, Meal, AppTheme } from '../core/constants/types';

export interface AppContextType {
  themeMode: AppTheme;
  setThemeMode: React.Dispatch<React.SetStateAction<AppTheme>>;
  currentScreen: Screen;
  setCurrentScreen: React.Dispatch<React.SetStateAction<Screen>>;
  screenStack: Screen[];
  setScreenStack: React.Dispatch<React.SetStateAction<Screen[]>>;
  go: (s: Screen) => void;
  back: () => void;
  activeTab: string | null;
  switchTab: (tabId: string) => void;
  resetNavigation: (screen: Screen) => void;
  isDark: boolean;
  t: T;
  
  toast: string | null;
  setToast: React.Dispatch<React.SetStateAction<string | null>>;

  user: any;
  setUser: React.Dispatch<React.SetStateAction<any>>;
  subscribed: boolean;
  setSubscribed: React.Dispatch<React.SetStateAction<boolean>>;
  newUserHomeMealTab: 'lunch' | 'dinner';
  setNewUserHomeMealTab: React.Dispatch<React.SetStateAction<'lunch' | 'dinner'>>;
  paused: boolean;
  setPaused: React.Dispatch<React.SetStateAction<boolean>>;
  selectedMealId: number;
  setSelectedMealId: React.Dispatch<React.SetStateAction<number>>;
  mealsList: Meal[];
  setMealsList: React.Dispatch<React.SetStateAction<Meal[]>>;
  
  mobileNumber: string;
  setMobileNumber: React.Dispatch<React.SetStateAction<string>>;
  otpCode: string;
  setOtpCode: React.Dispatch<React.SetStateAction<string>>;
  otpSent: boolean;
  setOtpSent: React.Dispatch<React.SetStateAction<boolean>>;
  otpCountdown: number;
  setOtpCountdown: React.Dispatch<React.SetStateAction<number>>;

  selectedFilter: string;
  setSelectedFilter: React.Dispatch<React.SetStateAction<string>>;
  selectedCategory: string;
  setSelectedCategory: React.Dispatch<React.SetStateAction<string>>;
  selectedCam: number;
  setSelectedCam: React.Dispatch<React.SetStateAction<number>>;

  showLocationPermission: boolean;
  setShowLocationPermission: React.Dispatch<React.SetStateAction<boolean>>;
  showMapSelection: boolean;
  setShowMapSelection: React.Dispatch<React.SetStateAction<boolean>>;
  selectedMapPinIdx: number;
  setSelectedMapPinIdx: React.Dispatch<React.SetStateAction<number>>;
  selectedPlanId: string;
  setSelectedPlanId: React.Dispatch<React.SetStateAction<string>>;
  showManageOptions: boolean;
  setShowManageOptions: React.Dispatch<React.SetStateAction<boolean>>;
  checkoutMealPref: 'Veg' | 'Non-Veg';
  setCheckoutMealPref: React.Dispatch<React.SetStateAction<'Veg' | 'Non-Veg'>>;
  checkoutFreq: 'lunch' | 'dinner' | 'both';
  setCheckoutFreq: React.Dispatch<React.SetStateAction<'lunch' | 'dinner' | 'both'>>;
  checkoutCustomPrefs: string[];
  setCheckoutCustomPrefs: React.Dispatch<React.SetStateAction<string[]>>;
  checkoutStartDate: 'tomorrow' | 'custom';
  setCheckoutStartDate: React.Dispatch<React.SetStateAction<'tomorrow' | 'custom'>>;
  tourDate: string;
  setTourDate: React.Dispatch<React.SetStateAction<string>>;
  tourTimeSlot: string;
  setTourTimeSlot: React.Dispatch<React.SetStateAction<string>>;
  tourVisitors: number;
  setTourVisitors: React.Dispatch<React.SetStateAction<number>>;
  tourContactName: string;
  setTourContactName: React.Dispatch<React.SetStateAction<string>>;
  tourContactPhone: string;
  setTourContactPhone: React.Dispatch<React.SetStateAction<string>>;
  selectedAddress: string;
  setSelectedAddress: React.Dispatch<React.SetStateAction<string>>;
  addressDetails: string;
  setAddressDetails: React.Dispatch<React.SetStateAction<string>>;
  locationPermissionEnabled: boolean;
  setLocationPermissionEnabled: React.Dispatch<React.SetStateAction<boolean>>;
  searchQuery: string;
  setSearchQuery: React.Dispatch<React.SetStateAction<string>>;
  receiverDetailsName: string;
  setReceiverDetailsName: React.Dispatch<React.SetStateAction<string>>;
  receiverDetailsPhone: string;
  setReceiverDetailsPhone: React.Dispatch<React.SetStateAction<string>>;
  showPhotoPicker: boolean;
  setShowPhotoPicker: React.Dispatch<React.SetStateAction<boolean>>;
  showSearchModal: boolean;
  setShowSearchModal: React.Dispatch<React.SetStateAction<boolean>>;
  showLocationDialog: boolean;
  setShowLocationDialog: React.Dispatch<React.SetStateAction<boolean>>;
  addressesList: any[];
  setAddressesList: React.Dispatch<React.SetStateAction<any[]>>;
  addressLabel: 'Home' | 'Work' | 'Other';
  setAddressLabel: React.Dispatch<React.SetStateAction<'Home' | 'Work' | 'Other'>>;
  doorImageUri: string | null;
  setDoorImageUri: React.Dispatch<React.SetStateAction<string | null>>;
  mapTranslateX: number;
  setMapTranslateX: React.Dispatch<React.SetStateAction<number>>;
  mapTranslateY: number;
  setMapTranslateY: React.Dispatch<React.SetStateAction<number>>;
  mapOffsetList: { x: number; y: number };
  setMapOffsetList: React.Dispatch<React.SetStateAction<{ x: number; y: number }>>;
  isDraggingMap: boolean;
  setIsDraggingMap: React.Dispatch<React.SetStateAction<boolean>>;
  showContactsModal: boolean;
  setShowContactsModal: React.Dispatch<React.SetStateAction<boolean>>;
  deviceContacts: any[];
  setDeviceContacts: React.Dispatch<React.SetStateAction<any[]>>;
  contactsSearchQuery: string;
  setContactsSearchQuery: React.Dispatch<React.SetStateAction<string>>;

  setup3SubPage: number;
  setSetup3SubPage: React.Dispatch<React.SetStateAction<number>>;
  goalWeight: string;
  setGoalWeight: React.Dispatch<React.SetStateAction<string>>;
  workoutFrequency: string;
  setWorkoutFrequency: React.Dispatch<React.SetStateAction<string>>;
  workoutTypes: string[];
  setWorkoutTypes: React.Dispatch<React.SetStateAction<string[]>>;
  primaryGoal: string;
  setPrimaryGoal: React.Dispatch<React.SetStateAction<string>>;
  goalSpeed: string;
  setGoalSpeed: React.Dispatch<React.SetStateAction<string>>;
  motivation: string;
  setMotivation: React.Dispatch<React.SetStateAction<string>>;
  allergiesList: string[];
  setAllergiesList: React.Dispatch<React.SetStateAction<string[]>>;
  healthConditions: string[];
  setHealthConditions: React.Dispatch<React.SetStateAction<string[]>>;
  foodDislikes: string[];
  setFoodDislikes: React.Dispatch<React.SetStateAction<string[]>>;
  waterIntakeGoal: string;
  setWaterIntakeGoal: React.Dispatch<React.SetStateAction<string>>;
  customWaterIntake: string;
  setCustomWaterIntake: React.Dispatch<React.SetStateAction<string>>;
  bedtime: string;
  setBedtime: React.Dispatch<React.SetStateAction<string>>;
  wakeupTime: string;
  setWakeupTime: React.Dispatch<React.SetStateAction<string>>;
  smartNotifications: any;
  setSmartNotifications: React.Dispatch<React.SetStateAction<any>>;
  connectedHealthApps: string[];
  setConnectedHealthApps: React.Dispatch<React.SetStateAction<string[]>>;

  obFade: any;
  obSlideY: any;
  obScale: any;
  obIllusScale: any;
  splashFade: any;
  splashScale: any;
  splashTranslateY: any;
  obTitleSlideY: any;
  obTitleFade: any;
  obDescSlideY: any;
  obDescFade: any;
  obChipsFade: any;
  obBtnSlideY: any;
  obBtnFade: any;
  obFloatAnim: any;
  cardFloat1: any;
  cardFloat2: any;
  cardFloat3: any;
  authFade: any;
  authSlideY: any;

  detectCurrentLocation: (silent?: boolean) => Promise<void>;
  getNumericPrice: (p: string) => number;
  panResponder: any;
  
  activeMealIndex: number;
  setActiveMealIndex: React.Dispatch<React.SetStateAction<number>>;
  menuActiveTab: 'recipes' | 'customize';
  setMenuActiveTab: React.Dispatch<React.SetStateAction<'recipes' | 'customize'>>;
  plateScale: any;
  plateRotate: any;
  plateFade: any;
  calorieCalc: { target: number; protein: number; carbs: number; fat: number; fiber: number };
}

export const AppContext = createContext<AppContextType | undefined>(undefined);

export const useAppContext = () => {
  const context = useContext(AppContext);
  if (!context) {
    throw new Error('useAppContext must be used within an AppContextProvider');
  }
  return context;
};
