import { Meal } from './types';

export const IMG = {
  dal: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=800&h=500&fit=crop&auto=format',
  paneer: 'https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=800&h=500&fit=crop&auto=format',
  curry: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?w=800&h=500&fit=crop&auto=format',
  thali: 'https://images.unsplash.com/photo-1680993032090-1ef7ea9b51e5?w=800&h=500&fit=crop&auto=format',
  soup: 'https://images.unsplash.com/photo-1559561723-c3f4195835db?w=800&h=500&fit=crop&auto=format',
  rice: 'https://images.unsplash.com/photo-1743674453123-93356ade2891?w=800&h=500&fit=crop&auto=format',
  chicken: 'https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=800&h=500&fit=crop&auto=format',
  fish: 'https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&h=500&fit=crop&auto=format',
  idli: 'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&h=500&fit=crop&auto=format',
  salad: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&h=500&fit=crop&auto=format',
};

export const CATEGORIES = [
  'Lunch',
  'Dinner',
  'High Protein',
  'Healthy',
  'Kids',
  'Senior Meals',
  'Andhra',
  'North Indian',
  'South Indian',
  'Chef Specials'
];

export const MEALS: Meal[] = [
  // Monday
  {
    id: 1,
    name: 'Dal Tadka + Steamed Rice',
    img: IMG.dal,
    when: 'lunch',
    type: 'veg',
    categories: ['Lunch', 'Healthy', 'North Indian', 'Senior Meals'],
    cal: 380,
    protein: 14,
    carbs: 58,
    fat: 9,
    fiber: 6,
    serving: '420g',
    price: '₹149',
    rating: 4.8,
    reviewsCount: 124,
    time: '12:30 PM',
    desc: 'Creamy yellow lentils tempered with cumin, garlic, pure cow ghee, and dry chillies, served with fluffy white basmati rice.',
    chef: 'Chef Amrita Sen',
    isHealthy: true,
    isAvailableToday: true,
    day: 'Monday',
    ingredients: {
      oil: 'Cold Pressed Groundnut Oil',
      rice: 'Sona Masoori',
      veg: ['Fresh Local Onions', 'Vine Tomatoes', 'Green Chillies', 'Garlic', 'Ginger', 'Fresh Coriander'],
      spices: ['Everest Turmeric', 'MDH Chilli Powder', 'Coriander Powder', 'Tata Salt', 'Cumin Seeds', 'Mustard Seeds'],
      dairy: ['Nandini Cow Ghee'],
      dal: 'Unpolished Yellow Moong & Toor Dal'
    },
    reviews: [
      { id: 101, user: 'Priya K.', rating: 5, comment: 'Exactly like home! The dal was perfectly spiced, not heavy at all.', date: '2 days ago', verified: true, avatar: 'PK', helpful: 14 },
      { id: 102, user: 'Rohit M.', rating: 4, comment: 'Fresh and healthy. Delivery was spot on time.', date: '4 days ago', verified: true, avatar: 'RM', helpful: 9 },
      { id: 103, user: 'Suresh Rao', rating: 5, comment: 'Very soft and easy to digest. Great for seniors.', date: '1 week ago', verified: true, avatar: 'SR', helpful: 21 }
    ]
  },
  {
    id: 2,
    name: 'Paneer Butter Masala + Roti',
    img: IMG.paneer,
    when: 'dinner',
    type: 'veg',
    categories: ['Dinner', 'Chef Specials', 'North Indian'],
    cal: 420,
    protein: 18,
    carbs: 45,
    fat: 16,
    fiber: 5,
    serving: '400g',
    price: '₹189',
    rating: 4.9,
    reviewsCount: 148,
    time: '7:30 PM',
    desc: 'Fresh soft cottage cheese cubes cooked in a rich, sweet-tangy tomato-butter gravy, finished with 2 handmade soft whole-wheat rotis.',
    chef: 'Chef Sanjay Kapoor',
    isHealthy: true,
    isAvailableToday: true,
    day: 'Monday',
    ingredients: {
      oil: 'Cold Pressed Sunflower Oil',
      veg: ['Ripe Tomatoes', 'Cashew Nuts', 'Kasuri Methi', 'Green Cardamom', 'Onion Paste'],
      spices: ['MDH Garam Masala', 'Kashmiri Lal Mirch', 'Aachi Turmeric', 'Salt'],
      dairy: ['Milky Mist Paneer', 'Amul Butter', 'Amul Fresh Cream'],
      flour: 'Aashirvaad Fortified Wheat Flour'
    },
    reviews: [
      { id: 201, user: 'Bhargav S.', rating: 5, comment: 'Cottage cheese is super soft! Highly recommended.', date: 'Today', verified: true, avatar: 'BS', helpful: 18 },
      { id: 202, user: 'Neha Sharma', rating: 5, comment: 'Very premium taste. Not oily or greasy like restaurants.', date: '3 days ago', verified: true, avatar: 'NS', helpful: 7 }
    ]
  },
  // Tuesday
  {
    id: 3,
    name: 'Andhra Chicken Curry + Bagara Rice',
    img: IMG.chicken,
    when: 'lunch',
    type: 'non-veg',
    categories: ['Lunch', 'Andhra', 'High Protein', 'Chef Specials'],
    cal: 560,
    protein: 34,
    carbs: 65,
    fat: 14,
    fiber: 4,
    serving: '450g',
    price: '₹229',
    rating: 4.7,
    reviewsCount: 92,
    time: '12:30 PM',
    desc: 'Fiery, robust Andhra-style chicken curry cooked with roasted spices, Guntur red chillies, and fresh coconut, served alongside fragrant Bagara rice.',
    chef: 'Chef Venkatesh Gowda',
    isHealthy: false,
    isAvailableToday: true,
    day: 'Tuesday',
    ingredients: {
      oil: 'Freedom Refined Sunflower Oil',
      rice: 'Premium Basmati Rice',
      veg: ['Local Red Onions', 'Vine Tomatoes', 'Mint Leaves', 'Coriander', 'Green Chillies'],
      spices: ['Aachi Andhra Chicken Masala', 'Guntur Red Chilli Powder', 'Eastern Turmeric', 'Tata Salt'],
      dairy: ['Heritage Thick Curd'],
      meat: 'Fresh Halal Chicken'
    },
    reviews: [
      { id: 301, user: 'Kiran Dev', rating: 5, comment: 'Perfect Guntur spice kick! The rice matches the chicken beautifully.', date: 'Yesterday', verified: true, avatar: 'KD', helpful: 32 },
      { id: 302, user: 'Anil Kumar', rating: 4, comment: 'Extremely flavorful. Proper South Indian experience.', date: '5 days ago', verified: true, avatar: 'AK', helpful: 11 }
    ]
  },
  {
    id: 4,
    name: 'Double Egg Masala + Jeera Rice',
    img: IMG.curry,
    when: 'dinner',
    type: 'egg',
    categories: ['Dinner', 'High Protein', 'North Indian', 'Andhra'],
    cal: 440,
    protein: 22,
    carbs: 55,
    fat: 12,
    fiber: 4,
    serving: '420g',
    price: '₹169',
    rating: 4.5,
    reviewsCount: 88,
    time: '7:30 PM',
    desc: 'Two organic farm eggs boiled and gently sautéed in a spiced onion-tomato pan gravy with roasted cumin seeds and fresh cilantro.',
    chef: 'Chef Sanjay Kapoor',
    isHealthy: true,
    isAvailableToday: true,
    day: 'Tuesday',
    ingredients: {
      oil: 'Fortune Rice Bran Oil',
      rice: 'Sona Masoori',
      veg: ['Onions', 'Tomatoes', 'Capsicum', 'Ginger-Garlic Paste', 'Coriander'],
      spices: ['Everest Garam Masala', 'MDH Kasuri Methi', 'Turmeric Powder', 'Chilli Powder', 'Cumin Seeds']
    },
    reviews: [
      { id: 501, user: 'Vikas J.', rating: 4, comment: 'Superb high protein meal after my gym session.', date: '1 week ago', verified: true, avatar: 'VJ', helpful: 10 }
    ]
  },
  // Wednesday
  {
    id: 5,
    name: 'Kerala Avial + Red Rice',
    img: IMG.salad,
    when: 'lunch',
    type: 'veg',
    categories: ['Lunch', 'South Indian', 'Healthy', 'Senior Meals'],
    cal: 320,
    protein: 9,
    carbs: 52,
    fat: 8,
    fiber: 9,
    serving: '380g',
    price: '₹159',
    rating: 4.6,
    reviewsCount: 54,
    time: '12:30 PM',
    desc: 'A nutrient-dense traditional mix of drumstick, raw banana, carrot, and pumpkin simmered in a light coconut-yogurt paste.',
    chef: 'Chef Amrita Sen',
    isHealthy: true,
    isAvailableToday: true,
    day: 'Wednesday',
    ingredients: {
      oil: 'Cold Pressed Coconut Oil',
      rice: 'Kerala Basmati Rice',
      veg: ['Elephant Yam', 'Drumstick', 'Carrots', 'Raw Banana', 'Pumpkin', 'Curry Leaves'],
      spices: ['Freshly Ground Cumin', 'Green Chillies', 'Turmeric Powder', 'Salt'],
      dairy: ['Milky Mist Curd']
    },
    reviews: [
      { id: 401, user: 'Suresh P.', rating: 5, comment: 'Very authentic. The red rice is very nutritious.', date: '4 days ago', verified: true, avatar: 'SP', helpful: 5 }
    ]
  },
  {
    id: 6,
    name: 'Butter Chicken + Garlic Naan',
    img: IMG.chicken,
    when: 'dinner',
    type: 'non-veg',
    categories: ['Dinner', 'Chef Specials', 'High Protein', 'North Indian'],
    cal: 620,
    protein: 36,
    carbs: 70,
    fat: 22,
    fiber: 3,
    serving: '450g',
    price: '₹249',
    rating: 4.9,
    reviewsCount: 204,
    time: '7:30 PM',
    desc: 'Tandoori grilled chicken pieces simmered in a smooth, creamy tomato gravy with butter and fresh cream, served with handmade garlic naan.',
    chef: 'Chef Sanjay Kapoor',
    isHealthy: false,
    isAvailableToday: true,
    day: 'Wednesday',
    ingredients: {
      oil: 'Refined Oil',
      veg: ['Tomatoes', 'Garlic', 'Cashew Paste'],
      spices: ['Tandoori Masala', 'Garam Masala'],
      dairy: ['Butter', 'Cream'],
      meat: 'Chicken'
    },
    reviews: []
  },
  // Thursday
  {
    id: 7,
    name: 'Veg Pulao + Mix Veg Raita',
    img: IMG.rice,
    when: 'lunch',
    type: 'veg',
    categories: ['Lunch', 'Healthy', 'South Indian'],
    cal: 340,
    protein: 11,
    carbs: 54,
    fat: 8,
    fiber: 6,
    serving: '400g',
    price: '₹149',
    rating: 4.4,
    reviewsCount: 65,
    time: '12:30 PM',
    desc: 'Fragrant basmati rice cooked with fresh seasonal vegetables, mint, and mild spices, served with a refreshing cucumber-carrot curd raita.',
    chef: 'Chef Amrita Sen',
    isHealthy: true,
    isAvailableToday: true,
    day: 'Thursday',
    ingredients: {
      oil: 'Sunflower Oil',
      rice: 'Basmati Rice',
      veg: ['Carrots', 'Beans', 'Peas', 'Mint'],
      spices: ['Biryani Spices'],
      dairy: ['Curd']
    },
    reviews: []
  },
  {
    id: 8,
    name: 'Hyderabadi Chicken Biryani',
    img: IMG.thali,
    when: 'dinner',
    type: 'non-veg',
    categories: ['Dinner', 'Chef Specials', 'High Protein'],
    cal: 680,
    protein: 42,
    carbs: 85,
    fat: 18,
    fiber: 4,
    serving: '500g',
    price: '₹269',
    rating: 4.9,
    reviewsCount: 312,
    time: '7:30 PM',
    desc: 'Layers of long-grain basmati rice and juicy marinated chicken cooked on Dum in sealed pots with saffron, mint, and brown onions.',
    chef: 'Chef Venkatesh Gowda',
    isHealthy: false,
    isAvailableToday: true,
    day: 'Thursday',
    ingredients: {
      oil: 'Ghee',
      rice: 'Basmati Rice',
      veg: ['Mint', 'Onions', 'Coriander'],
      spices: ['Biryani Masala'],
      meat: 'Fresh Halal Chicken'
    },
    reviews: []
  },
  // Friday
  {
    id: 9,
    name: 'Rajma Masala + Basmati Rice',
    img: IMG.dal,
    when: 'lunch',
    type: 'veg',
    categories: ['Lunch', 'Healthy', 'North Indian'],
    cal: 410,
    protein: 15,
    carbs: 62,
    fat: 10,
    fiber: 8,
    serving: '440g',
    price: '₹149',
    rating: 4.7,
    reviewsCount: 106,
    time: '12:30 PM',
    desc: 'Red kidney beans slow cooked in a thick onion-tomato gravy with ginger-garlic paste and fresh coriander, served with steamed white rice.',
    chef: 'Chef Sanjay Kapoor',
    isHealthy: true,
    isAvailableToday: true,
    day: 'Friday',
    ingredients: {
      oil: 'Mustard Oil',
      rice: 'Basmati Rice',
      veg: ['Onions', 'Tomatoes', 'Ginger-Garlic'],
      spices: ['Turmeric', 'Coriander', 'Jeera']
    },
    reviews: []
  },
  {
    id: 10,
    name: 'Egg Curry + Soft Phulka',
    img: IMG.curry,
    when: 'dinner',
    type: 'egg',
    categories: ['Dinner', 'High Protein', 'South Indian'],
    cal: 430,
    protein: 20,
    carbs: 48,
    fat: 12,
    fiber: 5,
    serving: '410g',
    price: '₹159',
    rating: 4.5,
    reviewsCount: 74,
    time: '7:30 PM',
    desc: 'Boiled eggs cooked in a flavorful coconut-tomato curry base, served along with three freshly blown hot handmade wheat phulkas.',
    chef: 'Chef Venkatesh Gowda',
    isHealthy: true,
    isAvailableToday: true,
    day: 'Friday',
    ingredients: {
      oil: 'Sunflower Oil',
      veg: ['Tomatoes', 'Curry Leaves', 'Onions'],
      spices: ['Chilli Powder', 'Turmeric'],
      flour: 'Whole Wheat Flour'
    },
    reviews: []
  },
  // Saturday
  {
    id: 11,
    name: 'Kadhai Paneer + Butter Naan',
    img: IMG.paneer,
    when: 'lunch',
    type: 'veg',
    categories: ['Lunch', 'North Indian', 'Chef Specials'],
    cal: 480,
    protein: 19,
    carbs: 55,
    fat: 18,
    fiber: 4,
    serving: '430g',
    price: '₹199',
    rating: 4.8,
    reviewsCount: 135,
    time: '12:30 PM',
    desc: 'Paneer cubes tossed with bell peppers and freshly ground kadhai masala spices in an onion-tomato wok gravy, served with soft naan.',
    chef: 'Chef Sanjay Kapoor',
    isHealthy: true,
    isAvailableToday: true,
    day: 'Saturday',
    ingredients: {
      oil: 'Sunflower Oil',
      veg: ['Capsicum', 'Onions', 'Tomatoes'],
      spices: ['Kadhai Masala'],
      dairy: ['Paneer', 'Butter']
    },
    reviews: []
  },
  {
    id: 12,
    name: 'Chicken Masala + Chapati',
    img: IMG.chicken,
    when: 'dinner',
    type: 'non-veg',
    categories: ['Dinner', 'High Protein', 'Andhra'],
    cal: 510,
    protein: 32,
    carbs: 50,
    fat: 12,
    fiber: 4,
    serving: '420g',
    price: '₹209',
    rating: 4.6,
    reviewsCount: 84,
    time: '7:30 PM',
    desc: 'Dhaba style thick chicken curry cooked with dry roasted spices and whole peppercorns, served with three thin soft chapatis.',
    chef: 'Chef Venkatesh Gowda',
    isHealthy: true,
    isAvailableToday: true,
    day: 'Saturday',
    ingredients: {
      oil: 'Groundnut Oil',
      veg: ['Ginger', 'Onions', 'Garlic'],
      spices: ['Dhaba Garam Masala'],
      meat: 'Chicken'
    },
    reviews: []
  },
  // Sunday
  {
    id: 13,
    name: 'Sambar Rice + Veg Poriyal',
    img: IMG.rice,
    when: 'lunch',
    type: 'veg',
    categories: ['Lunch', 'South Indian', 'Healthy'],
    cal: 310,
    protein: 8,
    carbs: 58,
    fat: 6,
    fiber: 8,
    serving: '400g',
    price: '₹139',
    rating: 4.7,
    reviewsCount: 119,
    time: '12:30 PM',
    desc: 'Hot aromatic sambar mashed with rice and served with a side of dry-sautéed cabbage and carrot poriyal topped with fresh coconut.',
    chef: 'Chef Amrita Sen',
    isHealthy: true,
    isAvailableToday: true,
    day: 'Sunday',
    ingredients: {
      oil: 'Coconut Oil',
      rice: 'Sona Masoori',
      veg: ['Cabbage', 'Carrot', 'Pumpkin'],
      spices: ['Sambar Powder', 'Asafoetida', 'Mustard']
    },
    reviews: []
  },
  {
    id: 14,
    name: 'Mutton Curry + Steamed Rice',
    img: IMG.curry,
    when: 'dinner',
    type: 'non-veg',
    categories: ['Dinner', 'High Protein', 'Chef Specials'],
    cal: 610,
    protein: 38,
    carbs: 60,
    fat: 20,
    fiber: 3,
    serving: '450g',
    price: '₹299',
    rating: 4.9,
    reviewsCount: 156,
    time: '7:30 PM',
    desc: 'Tender premium mutton pieces slow braised in a spiced gravy with onions, yoghurt, and rich spices, served with soft basmati rice.',
    chef: 'Chef Sanjay Kapoor',
    isHealthy: false,
    isAvailableToday: true,
    day: 'Sunday',
    ingredients: {
      oil: 'Mustard Oil',
      rice: 'Basmati Rice',
      veg: ['Garlic', 'Ginger', 'Onions'],
      spices: ['Mutton Masala'],
      meat: 'Fresh Halal Mutton'
    },
    reviews: []
  }
];

export const PLANS = [
  { id: 'daily', name: 'Daily', badge: '', price: '₹180', unit: '/day', sub: 'Pay as you go · No commitment', color: '#4A4A4A', perks: ['1 meal slot', 'Any cuisine', 'Cancel anytime'] },
  { id: 'weekly', name: 'Weekly', badge: 'POPULAR', price: '₹1,099', unit: '/week', sub: '₹157/day · Save 13%', color: '#E96A2E', perks: ['Lunch + Dinner', '14 meals', '1 skip per week'] },
  { id: 'monthly', name: 'Monthly', badge: 'BEST VALUE', price: '₹3,999', unit: '/month', sub: '₹133/day · Save 26%', color: '#6366F1', perks: ['Lunch + Dinner', '60 meals', 'Pause anytime', 'Priority support'] },
  { id: 'family', name: 'Family', badge: '', price: '₹6,999', unit: '/month', sub: 'For 2 people · ₹3,500/person', color: '#EC4899', perks: ['2 dabba sets', 'All meals included', 'Custom preferences'] },
  { id: 'student', name: 'Student', badge: '', price: '₹2,499', unit: '/month', sub: 'Valid student ID required', color: '#0EA5E9', perks: ['Lunch only', '25 meals', 'Student pricing'] },
  { id: 'corporate', name: 'Corporate', badge: '', price: '₹8,999', unit: '/month', sub: 'For 5+ employees', color: '#8B5CF6', perks: ['Bulk pricing', 'Office delivery', 'Invoice & GST'] },
];

export const MOCK_MAP_LOCATIONS = [
  { id: 1, name: 'Jubilee Hills Road', house: 'Plot 42', landmark: 'Near Metro Station', pincode: '500033', label: 'Jubilee Hills, Hyderabad', x: 25, y: 35 },
  { id: 2, name: 'Indiranagar 100ft Road', house: 'Villa 15', landmark: 'Opposite Metro Pillar 114', pincode: '560038', label: 'Indiranagar, Bengaluru', x: 75, y: 30 },
  { id: 3, name: 'Gachibowli High Street', house: 'Flat 304, Cyber Heights', landmark: 'Beside DLF IT Park', pincode: '500032', label: 'Gachibowli, Hyderabad', x: 30, y: 70 },
  { id: 4, name: 'HSR 27th Main', house: 'Suite 101, Prestige Court', landmark: 'Behind Shell Fuel Station', pincode: '560102', label: 'HSR Layout, Bengaluru', x: 70, y: 75 },
];
